### ISSUE TITLE
Using junit reporter with cucumber-boilerplate seems to not work

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/wdio-junit-reporter#34]
_From @inspiraller on March 29, 2017 9:9_

Using cucumber-boilerplate with  junit reporter, I get an error:
This is inside my wdio.conf:

```javascript
    reporters: ['spec','junit'],
    reporterOptions: {
        junit: {
            outputDir: './reports/'
        }
    },  
```

This is the error:
```
cucumber_boilerplate_prototype\node_modules\webdriverio\build\lib\utils\BaseReporter.js:336
                        throw _iteratorError;
                        ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at JunitReporter.prepareName (c:\projects\cucumber_boilerplate_prototype\node_modules\wdio-junit-reporter\build\reporter.js:98:24)
    at JunitReporter.prepareXml (c:\projects\cucumber_boilerplate_prototype\node_modules\wdio-junit-reporter\build\reporter.js:147:57)
    at JunitReporter.onEnd (c:\projects\cucumber_boilerplate_prototype\node_modules\wdio-junit-reporter\build\reporter.js:75:36)
    at emitOne (events.js:77:13)
    at JunitReporter.emit (events.js:169:7)
    at BaseReporter.handleEvent (c:\projects\cucumber_boilerplate_prototype\node_modules\webdriverio\build\lib\utils\BaseReporter.js:324:35)
    at Launcher.endHandler (c:\projects\cucumber_boilerplate_prototype\node_modules\webdriverio\build\lib\launcher.js:637:28)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

_Copied from original issue: webdriverio/cucumber-boilerplate#73_

**Comment by christian-bromann** [comment]
Did you experience this @wvankuipers ?

**Comment by chadbrogan** [comment]
I am running into the exact same error with Jasmine 2.5.3 when I have a test marked as excluded `xit`.

**Comment by chadbrogan** [comment]
Skipped tests have an undefined value for the title attribute, which throws an error on `prepareName(...)`

https://github.com/webdriverio/wdio-junit-reporter/blob/2521ab547ac1ac8898b9f71c3ee56da00a4d1aee/lib/reporter.js#L74

Is that a legitimate situation, having an `undefined` title in a pending spec? I'm working on a pull request to more gracefully handle this situation. Would this be a good approach, or there something further upstream that needs to be looked at?

```es2015
    prepareName (name) {
        if (name) {
            return name.toLowerCase().split(this.suiteNameRegEx).filter(
                (item) => item && item.length
            ).join('_')
        }
        return ''
    }
```

**Comment by drawm** [comment]
In my case, there is a undefined value after each Scenario. I do not have a blank title.
Heres a test feature and step.
```

**Comment by wvankuipers** [comment]
> Did you experience this @wvankuipers ?

@christian-bromann I have not used the junit reporter in combination with the boilerplate. I'm going to look into this.

**Comment by mfurtado-mdsol** [comment]
I am experiencing the same problem as @drawm.  I don't have any new lines after `Scenario` line but for some reason the `SuiteStats` object passed (as one of the keys of capabilities) into `prepareXml` method of `wdio-junit-reporter` from upstream contains 
``` { undefined:
       TestStats {
         type: 'test',
         start: 2017-05-10T14:29:40.961Z,
         _duration: 0,
         uid: 'undefined',
         title: undefined,
         state: '',
         screenshots: [],
         output: [] 
}
```

**Comment by mfurtado-mdsol** [comment]
@christian-bromann Do you have any idea on why this could be happening? Thanks.

**Comment by christian-bromann** [comment]
not without having a reproducible example

**Comment by mfurtado-mdsol** [comment]
@christian-bromann Here is a reproducible example repo: https://github.com/mfurtado-mdsol/junit-cucumber-failure.

I basically copied example given by @drawm with one difference(Before hook)  in my steps file.
```
var myStepDefinitionsWrapper = function () {

  this.Before(scenario => {
    // Do something
  });

  this.Given(/^blank test$/, function () {
  });
};
module.exports = myStepDefinitionsWrapper;
```

It seems to me adding a `Before` hook leads to this issue of undefined newline after Scenario title.

**Comment by christian-bromann** [comment]
`this.Before` is not supported by `wdio-cucumber-framework`. Please use wdio hooks. If it is supported in Cucumber `v1.x.x` than I am happy to add support for it. PRs welcome.

**Comment by mfurtado-mdsol** [comment]
@christian-bromann thanks. I can live with using wdio hooks. 🍻
