### ISSUE TITLE
Crash: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Kignuf** [webdriverio/wdio-junit-reporter#65]
Hello, I'm sometimes experiencing a crash in wdio-junit-reporter (using v0.3.0).

```
/Users/kevin.roulleau/source/happn-test-automation-appium/node_modules/webdriverio/build/lib/utils/BaseReporter.js:336
                        throw _iteratorError;
                        ^
TypeError: Cannot read property 'toLowerCase' of undefined
    at JunitReporter.prepareName (/Users/kevin.roulleau/source/happn-test-automation-appium/node_modules/wdio-junit-reporter/build/reporter.js:98:24)
    at JunitReporter.prepareXml (/Users/kevin.roulleau/source/happn-test-automation-appium/node_modules/wdio-junit-reporter/build/reporter.js:147:57)
    at JunitReporter.onEnd (/Users/kevin.roulleau/source/happn-test-automation-appium/node_modules/wdio-junit-reporter/build/reporter.js:75:36)
    at emitOne (events.js:96:13)
    at JunitReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (/Users/kevin.roulleau/source/happn-test-automation-appium/node_modules/webdriverio/build/lib/utils/BaseReporter.js:324:35)
    at Launcher.endHandler (/Users/kevin.roulleau/source/happn-test-automation-appium/node_modules/webdriverio/build/lib/launcher.js:651:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

I'm not sure what causes this in my test report, but I will investigate as soon as I get some time.

**Comment by christian-bromann** [comment]
Continue convo in #67
